#ifndef TICFOCUSER_CONFIG_H
#define TICFOCUSER_CONFIG_H

#define TICFOCUSER_VERSION_MAJOR @TICFOCUSER_VERSION_MAJOR@
#define TICFOCUSER_VERSION_MINOR @TICFOCUSER_VERSION_MINOR@

#endif // TICFOCUSER_CONFIG_H